using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeckTracker.Models
{
    public class MetaDecks
    {
        public List<string> DeckCodes;
        public List<Deck> Decks;
        public MetaDecks() 
        {
            DeckCodes = new List<string>
            {
                "CUDQCBQGDIAQMAISAEDAEIQBAYBSEAIGBQCQCBQHAUAQMBIGAYAQMAAKAEDACIQBAYESQAIGBQNACBQHAQBAMBAHBACACBQJAYAQMBBFAEDAOKACAYBBOGI",
                "CECACAQDBEBACAYTFIBQCBIWFAYQMBQFBQGQ4EA4EAAQEAIDFY4AA",
                "CICQCAQBAIAQKBQBAEDAMHQCAUAQMDYHAIDBEFBAEEUC2OQCAEAQCBYBAIDCMAA",
                "CQDACAYCAIAQGBASAECAIEABAUFFIAIGBINAKAIEBQOCOKBNAIAQMCRNAMCQVCABSEA2MAICAEAQIAIBAYFCQ",
                "CECACBQBEQAQMBJAAIAQKAJIAQBQCAYGBILAEAIEAEGAMAIBAEGBIJZKGQBACAIFDEAQGAIT",
                "CMCACBQHAUBACBBIGQBQIBABAICAIBAHAEOE6UYDAECAIBYBAUCBSAYEA5GWJCQBAA",
                "CECQCBABBQAQMAJEAEDAKIACAECQCKADAMAQGBQKAIAQGAIWAYAQCAIMCQTSUNACAEAQKGIBAMARG",
                "CMBQCBQHGMBAKBYLBYDAIBYDBUOCKJSZAIAQKBYHAUCAOO2IJRWXSAIBAQDT4",
                "CECQCAICBEAQIAQOAEDAECIDAECRKFZKAMDAKEBGFECACAICBQAQIAQIAEDAKIADAYBBOIRFAEAQCARR",
                "CQCACBIHBMAQMCRHAMCQUSNDAHKACBAEA4GSMSKZAQAQKBYHAEDAOMYCAQDSKOYCAUFBXJQBAEAQIB4KAE",
                "CECACBIACUBAIAAEBABAMABJFMEACAABAQDAYFBCEQTQAAIBAYACK",
                "CUCQCBAHQIAQCBQCEIAQMAZCAEDAKBQDAYDQIBJGAQAQMAAKAEDACIQBAYGASBAEA45V2Z4AAEBQCBQHFABAIBYURIAQEBQJEAUA",
                "CQCACBIBB4BAKCRRUYAQGAIBAMETEAYGBIHRCFIDAECACCQCAUFBVGABAIDAUCYTAMAQKCQBAEDAUFYBAYASA",
                "CICQCAYBAIAQKAIPAIAQCCIWAIBQSFZDAUDASCAQCEOR6AYBAMERGAIGAEOACBQJB4AQCBQJEM",
                "CECQCAYECIAQKAYGAEDAGKIEAEBQOFBHG4CQCBAMDQTSQLIBAIAQIAINAA",
                "CEAQGBQEBYKSQBYBAEBDCAIBAQ2ACAQCAMAQGBADAEDAIFQCAQCAEBYDAYBA4IBEA4AQCBA3AEBQEFABAUCBCAIGAIGQEAICBQUQEAQCAUEQGBQECIQCW",
                "CEBAEAIFAEUAOAIEAQNSIMBUGU4AEAYBAUOTCNQDAECB6OJ2AEAQCBJC",
                "CEBAGAIDEQXDMBQBAIEASDYYFM4AEAQBAILDCAYBAMFBMMQCAEAQGMICAEBAWEQ",
                "CEBACAIDFIDQCAQGBAIRULBRHEBAEAICAILAGAIDBQKBWAQBAEBASBIBAMMSGKZWG4",
                "CEBAEAICAIYQQAIBAMDQSFAWEEUTCAQBAEATIAYBAIQS2OICAEAQEHABAEASO",
                "CEBACAIDCQFACAABAICAMCQTDURCOMYBAMAQADYWDIAQCAIABQ",
                "CEDAGBQFBQIBYAIFAUFQCAQDBEAQCBJRAEAQGNYBAUBQ6BADAYCQ2DRAAEAQKKACAEBSULQBAQBRMAICAECQGNI",
                "CEDACAYECIBAMCQ2FUCACBAMDQTSQAIEAQIACBIKKQAQGAQCAIBQKCUIAGIQDJQBAEAQILICAECQUKQBAECAC",
                "CEEACBQHAUAQMARCAEDAICABAYFBYAIGAMRACBQABIAQMAJCAIDAYBI2AYAQMBQ2AEDAOBABAYCQMAIGAAFQCBQBCIAQMCJIAEAQMBZI",
                "CECQCBQDFEBACAYMFIBQGCJMGZMACBAJBUAQEAYDAMBQCAYCFA3QGAYJDIOCGAIGBEVACAQGAMLCO",
                "CECACBQFEACAGAIDAYFBMAQBAUASQAIGAESAEBQBAEAQYFBHFI2ACBABBQBACAIFDEAQGAIT",
                "CECQOAQGCQQCCJRIFU5ACBIGAEBAKAIGB4AQMBQ6AEBACAQCAEBAMEQBAYDB2AA",
                "CIDACBAFB4AQMBRGAEDAKKYCAECQCKACAICQQCQEAIDBOLZVHAAQGAQGDUTSYAIBAIDB4",
                "CECACAIDFIAQEAYJAMAQKFRIGEBQMBIOCAOAEAQBAMJTQBAGAUGA2IBGAQAQCAZOAEAQKNIBAQBQEAIGAUSQ",
                "CUCACBAHQIAQCBQCEIAQMAZCAIDAOBJGA4AQMAJCAEDAEGIBAYESQAIGAQDQCBQMBEAQMBYEAUCAOO25M6AADCQBAMAQIBYUAECQOFQBAYDSQ",
                "CUFACAIEGYAQEBR4AEBQKBQBAQEQ2AIFAEDACBQCAMAQMAYMAEDAYAQCAIBQGBADAEBQEDBIAAAQCAIDFY",
                "CICACAIFFAAQICINAEDAKIAGAMERULBWJFMNSAIDAEDASJQCAECQCGIDAMEROHBDAEAQMCJN",
                "CUDACAIADUAQEAACAECQADABAYCAQAIGA4CAMBQABMIRKGA3DUBACBQBCIAQMDA2AMAQEAAGAEDAAEQBAYEQM",
                "CECQCAIFAEAQIBIFAEDAKIACAMAQECIFAEAQGCYSEYUAEAIGAEOQGAIBAEPCUAQBAEATOAIBAUBQ",
                "CEDACAQCAUAQEAYJAECQEBYBAYBAUAYBAIEAYDYDAEBSULRXAMAQMAQOAEDAGDICAEBC4MICAEAQGEYBAMBBI",
                "CMDACAIABUAQEAACAECAAAYBAQDXSAIFAAGAGBQHA4EQUBQBAEAASAICAACACAYABYAQKAAOAEDAOCACAQDTWSQCAECAO3IBAYDSQ",
                "CQCACBQFEABACBIBFABAKBIIBEDQKCRRHFOV4YUYAGTACAABAQAQKDYTCQOQ",
                "CQCACAYECQBQCBAIDE5AGBIEAIDA4BAFBICKIANGAHPQCAQBAECDIAQFBIUNCAIBAECQURQ",
                "CQBQEAIFAEUAGBQKB4IRKBAFBIYXRGABUYAQGAIFBI2ACBQFEABACBJRGUCQCAIFB4AQGBIIAECQUAIBAYFBOAIGAUKA",
                "CECACAYBAIAQIAYEAIAQGBBBAMAQCFQ6EYBQCBADAIBQCAY7GM2QIAIBAMFSSMACAECQCDYCAEAQCKQ",
                "CUDQCAIEDQAQIBAHAEDAMHQBAYCBMAIGBQDACBQFEABQCBIBFAVQGAIBAEOQCBABBICACBIPEIXDCAIBAQDVG",
                "CECQCAYDB4AQGBASAEDAGKIDAEBQYFBHAQAQIDBHFAWQEAQBAMDTOAYBAQAQ2HAA",
                "CEDQCAQBAYAQIAYSAECQCDYCAEAQSIYCAYAREIYCAYBSOKIDAEBQMHRQAEAQGAICAIAQGAIUAEDACFA",
                "CEBACAQCAMBAMBAVFAAQCAYEAMEQCAYCCQAQGBALAECAIBYBAUCBCBABAIFQYKJRAUAQIAIQDMQTIBICAIBAKCAJBICQMAQBBUHCAJAGAYCASDQSCYQCW",
                "CICQCAYFAYAQICINAECAKCYBAYESUBYDBENCGLBWHBEVQAYBAMCQEAIEBEHQCBQJEYAQCAYJBU"


            };
            Decks = new List<Deck>();
        }
    }

    public class Deck
    {
        public HashSet<string> Cards { get; set; }

        public Deck()
        {
            Cards = new HashSet<string>();

        }

    }
}
